### ISSUE TITLE
Not able to run abs.so file with tensorflow=1.12.0

### ISSUE THREAD

**Issue by hassanali-khatim** [naiyeleo/ABS#2]
Dear Author,
I am trying to reproduce your results in my experiments.

However, I am unable to use "python2 run_abs.py". The error I get is given as follows with a full traceback:

**Traceback (most recent call last):
  File "run_abs.py", line 1, in <module>
    import abs
  File "abs.pyx", line 29, in init abs
AttributeError: 'module' object has no attribute 'set_random_seed'**

I have tried downgrading my tensorflow to 1.12.0, but it doesn't help. Would appreciate your help here.

Thanks

**Comment by hassanali-khatim** [comment]
I have removed the same error in the file "test_all.py", by simply replacing "set_random_seed" with "random.set_seed". However, I cannot edit "abs.so", so I am stuck.

**Comment by naiyeleo** [comment]
Line 29 is `tf.set_random_seed(random_seed)` and `random_seed` is defined in config file.
`tf.set_random_seed()` is removed in tf2 and it seems that your tensorflow is not the correct version.

**Comment by hassanali-khatim** [comment]
I have tried downgrading my tensor-flow version to 1.12.0, as suggested in the "readme". However, this doesn't solve the problem either.

**Comment by naiyeleo** [comment]
what is the result of `python2 -c 'import tensorflow as tf; print(tf.__version__)'`

**Comment by hassanali-khatim** [comment]
It shows **'2.1.0'**. It turns out that when I downgraded my tensorflow to 1.12.0, I accidentally did it for python3. Thank you for pointing out.
After correcting the previous mistake, now I get **'1.12.0'**. I will create a new thread if I encounter another error. Thanks again.
