### ISSUE TITLE
possibly missing directory/files

### ISSUE THREAD

**Issue by EdwardKSG** [naiyeleo/ABS#4]
I was trying to run the round 4 code at TrojAI_competition/round4/abs_pytorch1_color_simple_filter4_11_9_d_classifier.py

There is a directory defined as a global variable: trained_triggers_dir = '/trained_triggers'
Seems files in that folder are used during filter check, for example: delta_name = trained_triggers_dir+'/gotham/deltas/id-00000142_model_18_464_900_4_11.pkl'

I got some errors while running as the directory ''/trained_triggers'' doesn't exist. I didn't find another directory with those filter files either. Would you mind uploading the files? or should I generate the files in some way? Thank you :)

**Comment by naiyeleo** [comment]
The trained_triggers is uploaded
